exclude-labels:
  - skip changelog

name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

change-template: '- $TITLE (#$NUMBER)'
change-title-escapes: '\<*_&'
replacers:
  # Remove conventional commits from titles
  - search: '/- (build|chore|ci|depr|docs|feat|fix|perf|refactor|test)(\(.*\))?(\!)?\: /g'
    replace: '- '

autolabeler:
  - label: breaking
    title:
      # Example: feat!: ...
      - '/^(build|chore|ci|depr|docs|feat|fix|perf|refactor|test)(\(.*\))?\!\: /'
  - label: build
    title:
      - '/^build/'
  - label: internal
    title:
      - '/^(chore|ci|refactor|test)/'
  - label: deprecation
    title:
      - '/^depr/'
  - label: documentation
    title:
      - '/^docs/'
  - label: enhancement
    title:
      - '/^feat/'
  - label: fix
    title:
      - '/^fix/'
  - label: performance
    title:
      - '/^perf/'

categories:
  - title: ðŸ† Highlights
    labels: highlight
  - title: ðŸ’¥ Breaking changes
    labels:
      - breaking
  - title: ðŸš€ Performance improvements
    labels: performance
  - title: âœ¨ Enhancements
    labels: enhancement
  - title: ðŸž Bug fixes
    labels: fix
  - title: ðŸ“– Documentation
    labels: documentation
  - title: ðŸ“¦ Build system
    labels: build
  - title: ðŸ› ï¸ Other improvements
    labels:
      - deprecation
      - internal

version-resolver:
  minor:
    labels:
      - breaking
  default: patch

template: |
  $CHANGES
