[alias]
arrow = "run --manifest-path ./rsql_cli/Cargo.toml -- --url arrow://datasets/users.arrow"
avro = "run --manifest-path ./rsql_cli/Cargo.toml -- --url avro://datasets/users.avro"
brotli = "run --manifest-path ./rsql_cli/Cargo.toml -- --url brotli://datasets/users.csv.br"
bzip2 = "run --manifest-path ./rsql_cli/Cargo.toml -- --url bzip2://datasets/users.csv.bz2"
csv = "run --manifest-path ./rsql_cli/Cargo.toml -- --url csv://datasets/users.csv"
delimited = "run --manifest-path ./rsql_cli/Cargo.toml -- --url delimited://datasets/users.pipe?delimiter=|"
duckdb = "run --manifest-path ./rsql_cli/Cargo.toml -- --url duckdb://datasets/users.duckdb"
excel = "run --manifest-path ./rsql_cli/Cargo.toml -- --url excel://datasets/users.xlsx"
file = "run --manifest-path ./rsql_cli/Cargo.toml -- --url file://datasets/users.csv"
fwf = "run --manifest-path ./rsql_cli/Cargo.toml -- --url fwf://datasets/users.fwf?widths=4,15&headers=id,name"
gzip = "run --manifest-path ./rsql_cli/Cargo.toml -- --url gzip://datasets/users.csv.gz"
http = "run --manifest-path ./rsql_cli/Cargo.toml -- --url http://raw.githubusercontent.com/theseus-rs/rsql/refs/heads/main/datasets/users.csv"
https = "run --manifest-path ./rsql_cli/Cargo.toml -- --url https://raw.githubusercontent.com/theseus-rs/rsql/refs/heads/main/datasets/users.csv"
# libsql currently conflicts with the rusqlite crate; hopefully the limbo rewrite in Rust will resolve this
libsql = "run --manifest-path ./rsql_cli/Cargo.toml -- --url libsql://?memory=true"
lz4 = "run --manifest-path ./rsql_cli/Cargo.toml -- --url lz4://datasets/users.csv.lz4"
json = "run --manifest-path ./rsql_cli/Cargo.toml -- --url json://datasets/users.json"
jsonl = "run --manifest-path ./rsql_cli/Cargo.toml -- --url jsonl://datasets/users.jsonl"
ods = "run --manifest-path ./rsql_cli/Cargo.toml -- --url ods://datasets/users.ods"
orc = "run --manifest-path ./rsql_cli/Cargo.toml -- --url orc://datasets/users.orc"
parquet = "run --manifest-path ./rsql_cli/Cargo.toml -- --url parquet://datasets/users.parquet"
postgres = "run --manifest-path ./rsql_cli/Cargo.toml -- --url postgres://?embedded=true"
postgresql = "run --manifest-path ./rsql_cli/Cargo.toml -- --url postgresql://?embedded=true"
rusqlite = "run --manifest-path ./rsql_cli/Cargo.toml -- --url rusqlite://"
sqlite = "run --manifest-path ./rsql_cli/Cargo.toml -- --url sqlite://datasets/users.sqlite3"
tsv = "run --manifest-path ./rsql_cli/Cargo.toml -- --url tsv://datasets/users.tsv"
xml = "run --manifest-path ./rsql_cli/Cargo.toml -- --url xml://datasets/users.xml"
xz = "run --manifest-path ./rsql_cli/Cargo.toml -- --url xz://datasets/users.csv.xz"
yaml = "run --manifest-path ./rsql_cli/Cargo.toml -- --url yaml://datasets/users.yaml"
zstd = "run --manifest-path ./rsql_cli/Cargo.toml -- --url zstd://datasets/users.csv.zst"

#[target.x86_64-unknown-linux-gnu]
#linker = "clang"
#rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"
