[package]
authors.workspace = true
categories.workspace = true
description = "rsql mariadb driver"
edition.workspace = true
keywords.workspace = true
license.workspace = true
name = "rsql_driver_mariadb"
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
async-trait = { workspace = true }
file_type = { workspace = true }
rsql_driver = { path = "../../rsql_driver", version = "0.19.4" }
rsql_driver_mysql = { path = "../mysql", default-features = false, version = "0.19.4" }

[dev-dependencies]
anyhow = { workspace = true }
testcontainers = { workspace = true }
testcontainers-modules = { workspace = true, features = ["mariadb"] }
tokio = { workspace = true, features = ["macros", "rt"] }

[features]
default = ["tls-native-tls"]
tls-native-tls = ["rsql_driver_mysql/tls-native-tls"]
tls-rustls-aws-lc-rs = ["rsql_driver_mysql/tls-rustls-aws-lc-rs"]
tls-rustls-ring = ["rsql_driver_mysql/tls-rustls-ring"]
