[package]
authors.workspace = true
categories.workspace = true
description = "rsql https driver"
edition.workspace = true
keywords.workspace = true
license.workspace = true
name = "rsql_driver_https"
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
async-trait = { workspace = true }
file_type = { workspace = true }
futures-util = { workspace = true }
reqwest = { workspace = true, default-features = false, features = [
    "charset",
    "gzip",
    "http2",
    "json",
    "stream",
    "system-proxy",
] }
rsql_driver = { path = "../../rsql_driver", version = "0.20.0" }
tempfile = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
url = { workspace = true }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
rustls = { workspace = true, features = ["ring"], optional = true }
tokio = { workspace = true, features = ["fs"] }

[dev-dependencies]
rsql_driver_csv = { path = "../csv", version = "0.20.0" }
tokio = { workspace = true, features = ["macros", "rt", "rt-multi-thread"] }
wiremock = { workspace = true }

[features]
tls-native-tls = ["reqwest/native-tls"]
tls-rustls-aws-lc-rs = ["reqwest/rustls"]
tls-rustls-ring = ["dep:rustls", "reqwest/rustls-no-provider"]
