name: Fast checks

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-D warnings"

on:
  workflow_call:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Install Rust
        run: rustup toolchain install --no-self-update
      - name: Install cargo audit
        run: cargo install cargo-audit
      - name: Audit dependencies
        run: |
          cargo audit \
            --ignore RUSTSEC-2023-0071 \
            --ignore RUSTSEC-2024-0320 \
            --ignore RUSTSEC-2024-0436 \
            --ignore RUSTSEC-2025-0052 \
            --ignore RUSTSEC-2025-0134 \
            --ignore RUSTSEC-2025-0141 \
            --ignore RUSTSEC-2026-0097 \
            --ignore RUSTSEC-2026-0098 \
            --ignore RUSTSEC-2026-0099 \
            --ignore RUSTSEC-2026-0104 \
            --ignore RUSTSEC-2026-0173 \
            --ignore RUSTSEC-2026-0194 \
            --ignore RUSTSEC-2026-0195

  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Install Rust
        run: rustup toolchain install --no-self-update
      - name: Check the project
        run: |
          cargo check --workspace --all-targets --all-features

  clippy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Install Rust
        run: rustup toolchain install --no-self-update
      - name: Check lints
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          cargo clippy --all-targets --all-features --examples --tests

  deny:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Install Rust
        run: rustup toolchain install --no-self-update
      - name: Install cargo deny
        run: cargo install cargo-deny
      - name: Check licenses
        run: cargo deny check --allow duplicate

  doc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Install Rust
        run: rustup toolchain install --no-self-update
      - name: Check documentation
        env:
          RUSTDOCFLAGS: -D warnings
        run: cargo doc --workspace --no-deps --document-private-items --all-features

  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Install Rust
        run: rustup toolchain install --no-self-update
      - name: Check formatting
        run: cargo fmt --all --check
