[package]
authors.workspace = true
categories.workspace = true
description = "rsql rusqlite driver"
edition.workspace = true
keywords.workspace = true
license.workspace = true
name = "rsql_driver_rusqlite"
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
async-trait = { workspace = true }
file_type = { workspace = true }
rsql_driver = { path = "../../rsql_driver", version = "0.17.2" }
rsql_driver_sqlite = { path = "../sqlite", version = "0.17.2" }
rusqlite = { workspace = true, features = ["bundled-full"] }
sqlparser = { workspace = true }
url = { workspace = true }

[dev-dependencies]
rsql_driver_test_utils = { path = "../test_utils", version = "0.17.2" }
tokio = { workspace = true, features = ["macros", "rt"] }
